### ISSUE TITLE
컨퍼런스 추가 중 뒤로가기 버튼을 누를 시,  UI가 잘리는 현상

### ISSUE THREAD

**Issue by volta2030** [LeeJaeHyeon05/DevProject#39]
![image](https://user-images.githubusercontent.com/65960990/166462122-4e4941ef-5b20-4e36-a5d3-1328790f1f2e.png)

해당 현상이 발생하면서 정보 기입에 문제가 발생합니다.

**Comment by jundonghyun** [comment]
입력중에 뒤로가기하셨을때 발생하신건가요?

**Comment by volta2030** [comment]
넵 addConference관련 레이아웃을 wrap content로 변경하고  android:windowSoftInputMode="adjustPan"를 addconferences activbity에 추가해서 해결하였습니다.
