### ISSUE TITLE
AddConferencesActivity  클래스 findUploader() 질문입니다.

### ISSUE THREAD

**Issue by volta2030** [LeeJaeHyeon05/DevProject#40]
![image](https://user-images.githubusercontent.com/65960990/166586877-bed4b1f9-68c6-4600-a2c8-7e8499deeca1.png)

AddConferenceActivity에서 글쓰기를 누르면 findUploader가 제일 먼저 호출되더라구요
함수의 역할이 userInfo에 있는 아이디를 불러오는 것 같던데, 
이 부분을 추가하신 이유가 궁금합니다 :)

**Comment by jundonghyun** [comment]
addOnCompleteListener에서 결과값을 반환시키려고했는데 아무리해도 안되더라구요.. 검색하니깐 콜백형식으로 해야 반환된다고해서 https://stackoverflow.com/questions/52420903/how-to-return-value-in-oncompletelistener-for-android 요거보고 비슷하게 만들어봤습니다
