### ISSUE TITLE
EditConference의 FirebaseDelete에서 질문있습니다

### ISSUE THREAD

**Issue by jundonghyun** [LeeJaeHyeon05/DevProject#54]
documentID를 이용해서 문서를 삭제한뒤 바로 나오는 if문은 문서를 삭제하고 다시 같은 documentID로 문서 이름을 만들어 수정한 값을 넣어  재생성하는건가요?

`FirebaseIO.delete("conferenceDocument", DataHandler.conferDataSet[position][8] as String)
                    if(cloudWrite(conference.documentID as String, bitmap) && FirebaseIO.write("conferenceDocument", conference.documentID, conference)){
                        Toast.makeText(this, "편집 완료!", Toast.LENGTH_SHORT).show()`
이부분 입니다!

**Comment by volta2030** [comment]
네 맞습니다 해당 문서 전체를 삭제하고 삭제했던 document lD를 이용하여 다시 생성합니다

**Comment by volta2030** [comment]
코드 다시보니까 바로나오는 if문까지는 생각을  못했네요...  이미지 업로드시 어떤 문제가 있나요?

**Comment by jundonghyun** [comment]
아 제가 이미지 추가해서 업로드하는 걸 만들었는데 제 코드랑 합치기전에 헷갈려서 여쭤봤습니다! ㅎㅎㅎ
