### ISSUE TITLE
메인화면에서 아래로 당겼을때 새로고침이 되지 않습니다.

### ISSUE THREAD

**Issue by jundonghyun** [LeeJaeHyeon05/DevProject#66]

**Comment by volta2030** [comment]
![image](https://user-images.githubusercontent.com/65960990/168476307-4ab8c9be-9faa-455d-a130-fd3e33261f22.png)

binding과 binding에서 refreshLayout을 할당하는 과정이 뒤바껴있었더라구요.. 위 사진처럼 순서를 변경해서 해결했습니다 :)
